name: Main

on:
  push:
    branches:
      - main

jobs:
  trigger-website-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website build
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/plsr/website-next/dispatches \
            -d '{"event_type":"content_update"}'